WamsVideoLibrary/Controllers/AssetsController.cs
using System.Linq;
using System.Web.Mvc;
using WaMedia.Common;
using WaMediaWeb.Models;

namespace WaMediaWeb.Controllers
{
    public class AssetsController : BaseMediaController
    {
        //
        // GET: /Assets/

        public ActionResult Index()
        {
            var model = this.AssetService.Assets.OrderByDescending(a => a.MediaAsset.LastModified).ToList();
            return View(model);
        }

        public ActionResult CreateMediaAsset()
        {
            var tmpName = Server.MapPath("~/tmpuploads");
            if (!System.IO.Directory.Exists(tmpName))
            {
                System.IO.Directory.CreateDirectory(tmpName);
            }

            string pathToTempFile = System.IO.Path.Combine(tmpName, "Unknown");
            if (Request.Files.Count > 0)
            {
                var file = Request.Files.Get(0);
                pathToTempFile = System.IO.Path.Combine(tmpName, file.FileName);
                file.SaveAs(pathToTempFile);
            }
            else 
            {
                pathToTempFile = System.IO.Path.Combine(tmpName, Request.Params["qqfile"]);
                using (var fs = System.IO.File.Create(pathToTempFile))
                {
                    Request.InputStream.CopyTo(fs);
                    fs.Flush();
                }
            }
            this.AssetService.CreateAsset(pathToTempFile);
            System.IO.File.Delete(pathToTempFile);
            return Json(new { success = true });
        }

        public ActionResult CreateEmptyAsset(string name)
        {
            this.AssetService.CreateEmptyAsset(name);
            return RedirectToAction("index");
        }

        public ActionResult EncodeAndConvert(string assetId)
        {
            var assetToEncode = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateEncodeToSmoothStreamingJob(assetToEncode);
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult Details(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            if (asset == null)
            {
                return HttpNotFound();
            }
            return View(asset);
        }

        public ActionResult GetStreamingUrl(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            string streamingUrl = this.LocatorService.GetSmoothStreamingOriginLocator(asset);
            if (string.IsNullOrWhiteSpace(streamingUrl))
            {
                return HttpNotFound();
            }
            return View(new StreamingUrlViewModel() { Url = streamingUrl, IsMp4Progressive = false });

        }

        public ActionResult GetHlsStreamingUrl(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            string streamingUrl = this.LocatorService.GetHLSOriginLocator(asset);
            if (string.IsNullOrWhiteSpace(streamingUrl))
            {
                return HttpNotFound();
            }
            return View("GetStreamingUrl", new StreamingUrlViewModel() { Url = streamingUrl, IsMp4Progressive = false });
        }

        public ActionResult GetCDNStreamingUrl(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            string streamingUrl = this.LocatorService.GetSmoothStreamingAzureCDNLocator(asset);
            if (string.IsNullOrWhiteSpace(streamingUrl))
            {
                return HttpNotFound();
            }
            return View("GetStreamingUrl", new StreamingUrlViewModel() { Url = streamingUrl });

        }

        public ActionResult GetMp4StreamingUrl(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            string streamingUrl = this.LocatorService.GetMp4StreamingOriginLocator(asset);
            StreamingUrlViewModel model = new StreamingUrlViewModel();
            model.Url = streamingUrl;
            model.IsMp4Progressive = true;
            return View("GetStreamingUrl", model);
        }


        public ActionResult DecryptAsset(string assetId)
        {
            this.JobService.DecryptAsset(this.AssetService.GetAssetById(assetId));
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult PublishAsset(string assetId)
        {
            this.AssetService.Publish(assetId);
            return RedirectToAction("Index");
        }

        public ActionResult ConvertToMp4(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_ENCODER, Tasks.H264_HD_720P_CBR);
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult CreateThumbnails(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateThumbnails(asset);
            //this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_ENCODER, Tasks.H264_512k_DSL_CBR);
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult ConvertToPlayReady(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_ENCRYPTOR, this.JobService.GetPlayReadyTask(keySeed: PlayReady.DEV_SERVER_KEY_SEED, playReadyServerUrl: PlayReady.DEV_SERVER_LICENSE_URL));
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult ConvertToHls(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_PACKAGER, this.JobService.GetSmoothToHlsTask());
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult ConvertToMultiBitrateMp4(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_ENCODER, Tasks.H264_ADAPTIVE_BITRATE_SD_16x9);
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult Mp4ToSmooth(string assetId)
        {
            var asset = this.AssetService.GetAssetById(assetId);
            this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_ENCODER, Tasks.H264_Smooth_720p_3G_4G);
            //this.JobService.CreateNewJob(asset, MediaEncoders.WINDOWS_AZURE_MEDIA_PACKAGER, this.JobService.GetMp4ToSmoothTask());
            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult DeleteAsset(string assetId)
        {
            this.AssetService.DeleteAsset(assetId);
            return RedirectToAction("Index");
        }

        public ActionResult Rename(string assetId, string newName)
        {
            this.AssetService.Rename(assetId, newName);
            return RedirectToAction("Details", new { assetId = assetId });
        }

        public ActionResult GetSasUrl(string assetId)
        {
            var sasLoc = this.LocatorService.GetSasLocator(this.AssetService.GetAssetById(assetId));
            return View((object)sasLoc);
        }

        public ActionResult CopyFromBlob(string assetId, string srcBlob)
        {
            var src = this.LocatorService.GetSasLocator(this.AssetService.GetAssetById(assetId));
            this.AssetService.CopyFromBlob(src, srcBlob);
            return RedirectToAction("Details", new { assetId = assetId });
        }
    }
}

WamsVideoLibrary/Views/Assets/Details.cshtml
@model WaMedia.Common.Models.Asset

@{
    ViewBag.Title = "Asset Details";
    ViewBag.Message = @Model.MediaAsset.Name;
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<h2>Asset Details for @Model.MediaAsset.Name</h2>
State: @Model.MediaAsset.State<br />
Id: @Model.MediaAsset.Id
@using (Html.BeginForm("Rename", "Assets", FormMethod.Post))
{ 
    <div>
        <input type="text" name="newName" value="@Model.MediaAsset.Name" />
        <input type="hidden" name="assetId" value="@Model.MediaAsset.Id" />
        <br />
        <input type="submit" value="rename" />
    </div>
}
@using (Html.BeginForm("CopyFromBlob", "Assets", FormMethod.Post))
{
    <h3>Copy from Blob</h3>
   <div>
        <input type="text" name="srcBlob" value="" />
        <input type="hidden" name="assetId" value="@Model.MediaAsset.Id" />
        <br />
        <input type="submit" value="copy" />
    </div>
}
<h3>Files</h3>
<table border="0" cellpadding="3" cellspacing="2">
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Mime Type</td>
            <td>Encrypted</td>
            <td>Primary</td>
            <td>File Size</td>
    </tr>
    @foreach (var file in @Model.MediaAsset.AssetFiles)
    {
        <tr>
            <td>@file.Id</td>
            <td>@file.Name</td>
            <td>@file.MimeType</td>
            <td>@file.IsEncrypted</td>
            <td>@file.IsPrimary</td>
            <td>@file.ContentFileSize</td>
        </tr>
        
    }
</table>
<h3>Associated Locators</h3>
<table border="0" cellpadding="3" cellspacing="2">
     <tr>
        <th>Id</th>
        <th>Path</th>
        <th>Type</th>
     </tr>

 @foreach (var locator in @Model.MediaAsset.Locators)
 {
     <tr>
        <td>@locator.Id</td>
        <td>@locator.Path</td>
        <td>@locator.Type</td>
     </tr>
 }
</table>

WamsVideoLibrary/Views/Assets/GetSasUrl.cshtml
@model string
@{
    ViewBag.Title = "GetSasUrl";
}

<h2>SAS URL</h2>
@Model

WamsVideoLibrary/Views/Assets/GetStreamingUrl.cshtml
@model WaMediaWeb.Models.StreamingUrlViewModel

@{
    ViewBag.Title = "Streaming Url";
}
@section head{
   <!-- player skin -->
   <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/fwplayer-skin/minimalist.css")" />

   <!-- site specific styling -->
   <style>
   .flowplayer { width: 80%; }
   </style>
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}

    <script type="text/javascript">
        function onSilverlightError(sender, args)
        {
            var appSource = "";
            if (sender != null && sender != 0)
            {
                appSource = sender.getHost().Source;
            }

            var errorType = args.ErrorType;
            var iErrorCode = args.ErrorCode;

            if (errorType == "ImageError" || errorType == "MediaError")
            {
                return;
            }

            var errMsg = "Unhandled Error in Silverlight Application " + appSource + "\n";

            errMsg += "Code: " + iErrorCode + "    \n";
            errMsg += "Category: " + errorType + "       \n";
            errMsg += "Message: " + args.ErrorMessage + "     \n";

            if (errorType == "ParserError")
            {
                errMsg += "File: " + args.xamlFile + "     \n";
                errMsg += "Line: " + args.lineNumber + "     \n";
                errMsg += "Position: " + args.charPosition + "     \n";
            }
            else if (errorType == "RuntimeError")
            {
                if (args.lineNumber != 0)
                {
                    errMsg += "Line: " + args.lineNumber + "     \n";
                    errMsg += "Position: " + args.charPosition + "     \n";
                }
                errMsg += "MethodName: " + args.methodName + "     \n";
            }

            throw new Error(errMsg);
        }
    </script>

<h2>Here is the streaming URL for the requested Asset</h2>
@Model.Url

@if (Model.IsMp4Progressive)
{
       <!-- the player -->
   <div class="flowplayer" data-swf="@Url.Content("~/Scripts/flowplayer.swf")" data-ratio="0.417">
      <video>
         <source type="video/mp4" src="@Model.Url"/>
      </video>
   </div>
}
else
{
    <div id="silverlightControlHost" style="display: block; width: 100%; height: 100%;">
        <object data="data:application/x-silverlight-2," type="application/x-silverlight-2" width="100%" height="100%">
		  <param name="source" value="@Url.Content("~/Content/SmoothStreamingPlayer.xap")"/>
		  <param name="onError" value="onSilverlightError" />
		  <param name="background" value="white" />
		  <param name="minRuntimeVersion" value="5.0.61118.0" />
		  <param name="autoUpgrade" value="true" />
		  <param name="enableGPUAcceleration" value="true" />
		  <param name="InitParams" value="selectedcaptionstream=textstream_eng,mediaurl=@Model.Url" />
		  <a href="http://go.microsoft.com/fwlink/?LinkID=149156&v=4.0.50401.0" style="text-decoration:none">
 			  <img src="http://go.microsoft.com/fwlink/?LinkId=161376" alt="Get Microsoft Silverlight" style="border-style:none"/>
		  </a>
	    </object><iframe id="_sl_historyFrame" style="visibility:hidden;height:0px;width:0px;border:0px"></iframe>
    </div>
}

@section scripts
{
      <!-- include flowplayer -->
   <script src="@Url.Content("~/Scripts/flowplayer.min.js")"></script>

}

WamsVideoLibrary/Views/Assets/Index.cshtml
@using Microsoft.WindowsAzure.MediaServices.Client
@using WaMedia.Common

@model List<WaMedia.Common.Models.Asset>
@{
    ViewBag.Title = "Assets";
}
@section head
{
    <link href="@Url.Content("~/Content/fileuploader.css")" rel="stylesheet" type="text/css" />
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
@section scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/fileuploader.js")"></script>
    <script type="text/javascript">
        $(document).ready(function ()
        {

            var uploader = new qq.FileUploader({
                // pass the dom node (ex. $(selector)[0] for jQuery users)  -- change this
                element: $('#mediasource')[0],
                // path to server-side upload script
                action: '/Assets/CreateMediaAsset/',
                uploadButtonText: 'Create Media Asset'
            });


        });
    </script>
}
<h2>Create Empty Asset</h2>
@using (Html.BeginForm("CreateEmptyAsset", "Assets", FormMethod.Post))
{
    <input type="text" name="name" />
    <input type="submit" value="create" />
}
<h2>Assets List</h2>
<table border="0" cellpadding="4" cellspacing="2">
    <tr>
        <th>Name</th>
        <th>State</th>
        <th>Actions</th>
    </tr>
    @foreach (var asset in Model)
    {
        <tr>
            <td>          
            @asset.MediaAsset.Name</td>
            <td>@asset.MediaAsset.State</td>
            <td>
                @Html.ActionLink("[details]", "Details", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[streaming url]", "GetStreamingUrl", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[HLS URL]", "GetHlsStreamingUrl", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[streaming CDN]", "GetCDNStreamingUrl", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[progressive mp4 url]", "GetMp4StreamingUrl", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[Smooth enc.]", "EncodeAndConvert", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[Smooth Pack.]", "Mp4ToSmooth", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[HLS enc.]", "ConvertToHls", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[MP4 enc.]", "ConvertToMp4", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[Multi bitrate MP4 enc.]", "ConvertToMultiBitrateMp4", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[PlayReady ENC.]", "ConvertToPlayReady", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[Gen. Thumbnails]", "CreateThumbnails", new { assetId = @asset.MediaAsset.Id })
                @Html.ActionLink("[SAS URL]", "GetSasUrl", new { assetId = @asset.MediaAsset.Id });
                @Html.ActionLink("[~ DELETE ~]", "DeleteAsset", new { assetId = @asset.MediaAsset.Id })
           
                 </td>
        </tr>
    }
</table>
<div id="mediasource"></div>