WamsVideoLibrary/Controllers/MediaProcessorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaMediaWeb.Controllers
{
    public class MediaProcessorsController : BaseMediaController
    {
        //
        // GET: /MediaProcessors/

        public ActionResult Index()
        {
            return View(this.MediaService.MediaContext.MediaProcessors);
        }

    }
}

WamsVideoLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <script id='__csm_prefix' type='text/javascript'>var $$CsmPa = function () { var a = { a1: "27C1EB2C-E284-482A-9E93-32FF656FD6A8", ttfb: +new Date, A97: "1.0", a2: "\x2f\x2feus-cmt-cl1.tofino.windowsazure.com", a3: "js" }; this.a5 = a; (function () { var b = document.createElement("script"); b.type = "text/javascript"; b.src = a.a2 + "/Scripts/v" + a.A97 + "/" + a.a3 + "/analytics.js"; var c = document.getElementsByTagName("script")[0]; c.parentNode.insertBefore(b, c) })() }; if (typeof __csm_pa === "undefined") try { __csm_pa = new $$CsmPa } catch (exc) { } var _daCmds = _daCmds || []; _daCmds.push(["trackView"])</script>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("head", false);
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Wams Video Library", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        free access / no login
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Assets", "Index", "Assets")</li>
                            <li>@Html.ActionLink("Jobs", "Index", "Jobs")</li>
                            <li>@Html.ActionLink("Procs", "Index", "MediaProcessors")</li>
                            <li>@Html.ActionLink("Locators", "Locators", "Home")</li>
                            <li>@Html.ActionLink("~ RESET ~", "Reset", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>@DateTime.Now.Year - Use freely as you wish. at your own risk</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>